version: "3.8"

networks:
  django:
    external: true

services: 
  django-dev:
    container_name: django-dev
    image: django-dev
    build:
      context: ../../services/django_ms
      dockerfile: ../../docker/common/build/django_ms/Dockerfile
      target: development
    command: /bin/sh -c "cd /home/app/web && python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ../../services/django_ms:/home/app/web
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
      - "2501:22"
    networks:
      django:
        aliases:
          - ${DJANGO_HOST}
  
  postgres-dev:
    container_name: postgres-dev
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_development:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      django:
        aliases:
          - ${POSTGRES_HOST}

volumes:
  postgres_development:
